### ISSUE TITLE
Terminally broken bibliographgy entries

### ISSUE THREAD

**Issue by DanNixon** [DanNixon/sine2020_software_guidelines_paper#71]

**Comment by DanNixon** [comment]
@Anders-Markvardsen Please add the correct citation for Panosc: https://github.com/DanNixon/sine2020_software_guidelines_paper/blob/master/guidelines_for_collaborative_development_of_sustainable_data_treatment_software.tex#L141

**Comment by Anders-Markvardsen** [comment]
The panous link could be taken to be https://www.panosc.eu/ and similar for Expands https://expands.eu/....

Concerning this issue what is the difference between `Terminal broken` and `broken`? Is the purpose of this issue to fix all missing citations or just a few?

**Comment by DanNixon** [comment]
@Anders-Markvardsen The PANOSC citation is the only missing one.

**Comment by DanNixon** [comment]
Please open a PR.
